### ISSUE TITLE
Vimeo iframe embedded twice

### ISSUE THREAD

**Issue by gmlnchv** [vime-js/vime#123]
I'm using the following code inside a CraftCMS template:

```
<vime-embed 
          embed-src="https://player.vimeo.com/video/265045525"
          params="autoplay=1&muted=1&loop=1&controls=0" />
```

For some reason, 9 out of 10 times, it creates two identical iframes, as can be seen here:

![🚧_Homepage___TBWA_New_Zealand](https://user-images.githubusercontent.com/1403779/100177245-91747500-2f36-11eb-9db4-aa85d5481ae2.png)

Most of the time this actually works fine, however, every now and then the video doesn't autoplay unless one of the iframes is removed.

Any thoughts? Is this an expected behaviour?

**Comment by gmlnchv** [comment]
Looks like there is one difference between the two iframes in the screenshot above: `allowfullscreen` vs `allowfullscreen=1`. Not sure what that has got to do with anything though.

**Comment by mihar-22** [comment]
That's really odd and definitely shouldn't be happening, probably something to do with how Stencil is rendering the component because there is nothing too special in `vime-embed` that would mess up the rendering. This should be resolved in the next major release as I'm moving to `lit-element`. We can revalidate if the issue persists then and resolve it.

**Comment by mihar-22** [comment]
For now I don't really have any solutions because I can't see what would cause that at all.

Ref: https://github.com/vime-js/vime/blob/master/packages/core/src/components/core/embed/embed.tsx

**Comment by mihar-22** [comment]
Maybe cause I added a `// @ts-ignore`above allowfullscreen it's messing up.
