### ISSUE TITLE
FileProvider: recommended quality is too low

### ISSUE THREAD

**Issue by mihar-22** [vime-js/vime#33]
The quality that is initially loaded is too low, it should be one higher. For example, currently if the video player width is `410px` then a video with `360p` quality will be loaded instead of `480p` because it is closer. This results in a video that is stretched and of poor quality.

**Comment by silllli** [comment]
This does not seem to work for me. The first video source is always loaded as default. Or is there anything that needs to be done except adding an array of sources, like the following?

```
sources = [
  {
    quality: 720,
    src: "hd_video.mp4",
    type: "video/mp4",
  },
  {
    quality: 240,
    src: "sd_video.mp4“,
    type: "video/mp4",
  },
]
```

And is there a plan to adjust the quality after the initial load automatically? The problem is very obvious when opening a video in fullscreen that was previously played in a small player (and thus low quality).

**Comment by mihar-22** [comment]
Ye these are definitely issues which I've raised. Your implementation is correct, it's because Vime is looking at the size of the container and aspect ratio to find the closest quality to match. After that it's taking the next quality in the set. In this case it's a bug because it'll never use `240p`. I need to come up with a better algorithm for selecting qualities and updating them.
