### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by mehulmpt** [vime-js/vime#5]
Currently, the player does not include types and hence the typescript support is missing. Maybe this could be added somewhere on the roadmap later on to support typescript?

Thanks for the player!

**Comment by mihar-22** [comment]
Hey @mehulmpt that's definitely on the roadmap! Hopefully very soon.

**Comment by bmamouri** [comment]
Any update on TypeScript support?

**Comment by mihar-22** [comment]
Hey @bmamouri unfortunately not yet because I've been really busy with some other work. I'm planning on adding TS support and framework integrations next week.

**Comment by bmamouri** [comment]
Thank you @mihar-22, and well done on the great library.

**Comment by mihar-22** [comment]
Apologies on this issue because my other work has put me way off schedule for this library. I'm actually planning a version 2 rewrite which I'll make an announcement for hopefully soon 😅  I'm intending on rewriting the entire library in Typescript so that should automatically solve this issue. I'll reference this issue when I create the new announcement.

**Comment by mihar-22** [comment]
Closing this in favour of `v2`, feel free to provide any feedback!
