### ISSUE TITLE
Control pause / play

### ISSUE THREAD

**Issue by mr-islam** [vime-js/vime#61]
Hi, sorry if this is a really basic question, but I just started using Vime and I'm trying to control a standard player instance with a button by accessing the props in the store.

The `isPlaying` prop is read-only, but `paused` is controllable so I made a button to run this function to control pause and play:

    togglePlay = () => {
      paused.set(isPaused => {
        (!isPaused)
      })
    }

But, it cannot start playback in the player using this function – I have to click the player normally – but after that this function above can pause playback. But… it cannot restart playback either! I always have to start/resume playback from the player, and can only pause using the function.

Is this by design? Because my app depends on disabling the controls in the player, and instead I want to use HTML elements like a pause/play button *outside* the player

**Comment by mihar-22** [comment]
I'm not exactly sure if you're using JS or Svelte but you should be able to toggle playback directly on the player like so:

```js
const player = new Player({
  // ...
});

const togglePlayback = () => {
  player.paused = !player.paused;  
};
```

It also looks like you're using the player store and passing a callback into the setter `paused.set(cb)`, I don't think that would work because it's not part of the API unless I missed something.

At this time I'd recommend simply waiting for Vime 2 if it's for a serious project due to some poor design decisions I made in Vime 1. It should be 2 weeks out from release.

**Comment by mr-islam** [comment]
Yes, I should have mentioned I am using Svelte! 

I think I got confused and tried using the store's `set` method when I read this line in the docs and thought I have to use stores to access the props 😅️. 

> All props below are powered behind the scenes by a store. They are plain JS objects that contain a subscribe function and an optional set function. 

I just had a late-night urge to prototype something and got excited when I found Vime and had a series of brain-farts. But the docs are comprehensive and clear, amazing work! 

I'm looking forward to v2 very much then, the other issues indicates you'll improve the whole lite/standard/complete complexity, and I'd love to contribute a SoundCloud provider once v2 is out!

I'll close this issue then, thank you for your fast response :100:
