### ISSUE TITLE
Looking for Documentation on Implementation

### ISSUE THREAD

**Issue by jfreeze** [vime-js/vime#62]
Hi.

Sorry for the support request here, but I'm having trouble finding HTML examples using vime.js and where vime.js files can be loaded from using <script> tags. Also, I'm not able to find any slack, discord, or irc channels where vime.js developers hang out.

**Comment by mihar-22** [comment]
Hey @jfreeze I'm not sure what you exactly mean by HTML examples? At this time Vime can only be used via JS. If you want to load it directly into the page with a script, then you can refer to the [installation](https://vime-js.com/complete/setup#installation) section and click `UNPKG` or `JSDELIVR`. It also notes there that: 

> UMD builds are exported under the Vime namespace.

So basically `Vime.Player` or whatever you need. Currently there isn't a discord because this was only a hobby project by me but I'll be creating a discord for Vime 2. As I tell everyone if this is for a serious project then you should wait for Vime 2 which will be HTML based via web components and it'll resolve a lot of the mistakes in Vime 1.

Thanks!

**Comment by jfreeze** [comment]
Hi.

By HTML, I mean <video controls ....></video>. Is Vime.js created from a raw div?
Also, we seem to be having problems playing an external .m3u8 file.

I'm trying to get it to work at https://codesandbox.io/s/frosty-currying-xx6f5?file=/index.html with not much luck.

**Comment by mihar-22** [comment]
Oh yes Vime attaches to a simple `div` and you simply set the `src` property, `currentSrc` is readonly.

**Comment by mihar-22** [comment]
Oh and you most likely don't need the `blob:` prefix on the `src` unless it's some other requirement I'm unaware of.

**Comment by jfreeze** [comment]
Using <div> does not produce any video element.
Also, how do you set things like `control` and `type`?

```<div id="video" controls type="application/x-mpegURL"></div>

https://codesandbox.io/s/ancient-bush-tfvf5?file=/index.html

**Comment by mihar-22** [comment]
Everything is via JavaScript, you don't set anything on the mount point (`div`) other than an `id` attribute so you can reference it. Setting additional `src` properties like the `type` requires an object, refer to the [loading media guide](https://vime-js.com/guides/loading-media).

The Player API is available is available [here](https://vime-js.com/standard/api/player). If you're using `@vime-js/complete` then this [API](https://vime-js.com/complete/api/player) is also available.

As the example shows on the Complete setup guide make sure you load in the `Boot` plugin if you want the default Vime look.

Your example isn't working because you haven't loaded anything into the page. Move your JavaScript to the `index.js` file or load Vime via `unpkg` or `jsdelivr` like so:

`<script src="https://cdn.jsdelivr.net/npm/@vime-js/complete"></script>` and then you can use the `Vime` namespace like so `Vime.Player(...)`.

**Comment by jfreeze** [comment]
Thank you for all the help.

**Comment by jfreeze** [comment]
This seems to follow all of the requirements but still does not display a video.

https://codesandbox.io/s/ancient-bush-tfvf5?file=/index.html

**Comment by mihar-22** [comment]
Here's a working version -> https://codesandbox.io/s/muddy-wood-o47s4?file=/src/index.js.

Sorry about that seems like there's a bug with passing in a `src` object at the moment, you don't need it anyway. I think there may be something wrong with your HLS file because it seems to not parse/load.

**Comment by jfreeze** [comment]
Does Vime have a process for changing the src while a video is playing?
I suppose I could delete the whole div and recreate it, but changing player.src in the console just causes a spinner and the video becomes unresponsive.

**Comment by mihar-22** [comment]
It was coded to allow `src` changes but there's a bug when changing it with the `HlsProvider` which will be addressed in Vime 2.
