### ISSUE TITLE
@vime/vue: Crash when using with Nuxt.js

### ISSUE THREAD

**Issue by Ashot-KR** [vime-js/vime#68]
trying to use vime/vue in `nuxt.js` project, got exception `Cannot read property 'config' of undefined`
![image](https://user-images.githubusercontent.com/899218/91851103-4dd7db00-ec67-11ea-8f22-1209a317558d.png)

**Comment by borradaniele** [comment]
Same here, looks like the problem is in the way vue is required, at least in the commonjs builded files.
Inside components.js located under `@vime/vue/dist/cjs/components.js` vue is imported with a require in `vue_1` var. Then it is accessed with `vue_1.default` but this will throw an error with Nuxt. By replacing all the instances of `vue_1.default` with only `vue_1` the issue seems to be "fixed". Temporary of course.

**Comment by mihar-22** [comment]
Sorry about the delay on this one, trying to wrap up the v2 release. Thanks for digging into it @borradaniele, based on what you're saying it seems to be an issue upstream with how [stencil-ds-output](https://github.com/ionic-team/stencil-ds-output-targets) is generating the Vue components. I'll make a PR for it once I wrap all this up.

**Comment by borradaniele** [comment]
Perfect! Thank you for the amazing project!

**Comment by mihar-22** [comment]
This shouldn't of taken me 25 days to fix a simple TypeScript compiler flag missing 😅  All fixed now in the latest release `4.1.2` and I tested it with the latest release of Nuxt, everything works. At this point I'm sure you guys have moved on to Vue 3 haha, web world moves too fast to keep up... I'll eventually add support for that too, preferably soon.
